#!/bin/bash

# 检查 ~/.npm-global 文件夹是否存在，如果不存在则创建
if [ ! -d "~/.npm-global" ]; then
  mkdir ~/.npm-global
fi

# 设置 npm 的 prefix
npm config set prefix '~/.npm-global'

# 将 ~/.npm-global/bin 添加到 PATH
echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.bashrc
source ~/.bashrc

# 检查 pm2 是否已经安装，如果没有安装则安装
if ! command -v pm2 &> /dev/null; then
  npm install -g pm2
fi
